services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: assignment3
      MONGO_INITDB_ROOT_PASSWORD: assignment3
      MONGO_INITDB_DATABASE: geolife_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: